# Generated by Django 2.2.3 on 2019-08-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_documentsearch_relationsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationsearch',
            name='search_ptr',
        ),
        migrations.AlterModelOptions(
            name='search',
            options={},
        ),
        migrations.DeleteModel(
            name='DocumentSearch',
        ),
        migrations.DeleteModel(
            name='RelationSearch',
        ),
    ]
