# Generated by Django 2.2.3 on 2019-09-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190822_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp1', models.CharField(max_length=128)),
                ('kp2', models.CharField(max_length=128)),
                ('kp3', models.CharField(max_length=128)),
                ('document', models.CharField(blank=True, default='', max_length=128)),
                ('agenda_item_file', models.CharField(blank=True, default='', max_length=128)),
                ('agenda_item', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'permissions': [('search', 'Can search using the document search feature.')]},
        ),
        migrations.AddField(
            model_name='search',
            name='fbc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='fbc_council',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='search',
            name='fbc_publish_date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='fbc_publish_date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='fbm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='fbm_filename',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='search',
            name='fbm_upload_date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='fbm_upload_date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='fbm_uploader',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='search',
            name='key_phrase',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='search',
            name='key_phrase_importance',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='key_phrase_type',
            field=models.IntegerField(choices=[(0, 'Any keyword type'), (1, 'Councillor name'), (2, 'Person name'), (3, 'Business name'), (4, 'Property address')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='search_by',
            field=models.IntegerField(choices=[(0, 'Search by relation'), (1, 'Search by document')], default=0),
        ),
    ]
