# Generated by Django 2.2.3 on 2019-09-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20190902_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationResult',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
